java_library(
    name = "messenger-lib",
    srcs = ["Messenger.java"],
    visibility = [
        "//src/main/java/com/example:__pkg__",
        "//src/test/java/com/example/messenger:__pkg__"
    ],
    deps = [
        "@maven//:org_apache_commons_commons_lang3"
    ],
)