java_test(
    name = "messenger-test",
    srcs = [
        "MessengerTest.java"
    ],
    test_class = "com.example.messenger.MessengerTest",
    deps = [
        "//src/main/java/com/example/messenger:messenger-lib",
         "@maven//:junit_junit"
    ],
)